require File.dirname(__FILE__) + "/../.common/session.rb"

UBUNTU_SESSION =
  COMMON_SESSION.merge({ :boot_cmd_sequence =>
                         [ '<Esc>',
                           '<Esc>',
                           '<Enter>',
                           '/install/vmlinuz ',
                           'noapic ',
                           'preseed/url=http://%IP%:%PORT%/preseed.cfg ',
                           'debian-installer=en_US ',
                           'auto ',
                           'initrd=/install/initrd.gz ',
                           'locale=en_US ',
                           'kbd-chooser/method=us ',
                           'netcfg/get_hostname=%NAME% ',
                           'netcfg/get_domain=vagrantup.com ',
                           'fb=false ',
                           'debconf/frontend=noninteractive ',
                           'console-setup/ask_detect=false ',
                           'keyboard-configuration/layout=USA ',
                           'keyboard-configuration/variant=USA ',
                           ' -- ',
                           '<Enter>',
                         ],
                         :os_type_id => 'Ubuntu_64',
                         :postinstall_files => [ "apt_lang_remove.sh",
                                                 "update.sh", 
                                                 "virtualbox.sh",
                                                 "vagrant.sh",
                                                 "networking.sh",
                                                 "sudoers.sh",
                                                 "cleanup.sh",
                                                 "minimize.sh",
                                                 "compress_disk.sh"],
                         :kickstart_file => "preseed.cfg",
                         :shutdown_cmd => "/sbin/shutdown -h -P now" })
